### ISSUE TITLE
What does word_embeddings = tf.concat([special_word_embeddings, tf.constant(bert_word_embeddings[2:])], axis=0) mean?

### ISSUE THREAD

**Issue by zysNLP** [ztjfreedom/doc_representation#1]
Hi, I notice a "word_embeddings = tf.concat([special_word_embeddings, tf.constant(bert_word_embeddings[2:])], axis=0)" in your "doc_representation/2_IMDB_SMALL/dm_bert.py" in line 91. Can you explain why the bert_embedding remove the first two layer as [2:]? and why these bert_embeddings with shape 100? in your utils.load files? As far as I know, bert_serice get 768 hidden_size.

**Comment by ztjfreedom** [comment]
Thank you for your contact.
1. "bert_word_embeddings[2:]" doesn't mean to remove the first two layers. In my word vocabulary, the first two tokens are '<unk>' and '<pad>'. I replace them with special_word_embeddings with the purpose to learn them again using my own dataset, not only using the embeddings from transfer learning from BERT.
2. I reshape the embeddings to 100 only to save some memory. And since I'm trying to compare different solutions, I wish to keep all the embeddings from different solutions with a same dimension.
3. In addition, in this project, after BERT transfer learning, I use another unsupervised method to re-train / fine-tune the embeddings. If you are intended to solve some supervised learning problems, I recommend you to take a look at my "colab" repo. Some BERT examples are included.
Hope my answer helps.

**Comment by zysNLP** [comment]
OK, Thank you !
